[settings]
timeout = 1000
node_verifier = "None"

[relaychain]
default_command = "./binaries/polkadot"
chain = "rococo-local"

    [[relaychain.nodes]]
    name = "alice"
    validator = true
    ws_port = 9900
    extra_args = [ "-lparachain=debug" ]

    [[relaychain.nodes]]
    name = "bob"
    validator = true
    ws_port = 9901
    extra_args = [ "-lparachain=debug" ]

[[parachains]]
id = 2086
cumulus_based = true
chain_spec_path = "./plain-idchain-chainspec.json"

    [parachains.collator]
    name = "parachain-1-collator"
    command = "./binaries/idchain-parachain"
    ws_port = 9944
    args = ["--log=xcm=trace,pallet-assets=trace"]

# Add a second parachain if needed (e.g. for testing HRMP channels)
# but first need to compile a new binary with the new para id
# [[parachains]]
# id = 2087
# cumulus_based = true
# chain_spec_path = "./idchain-parachain-2-chainspec.json"

#     [parachains.collator]
#     name = "parachain-2-collator"
#     command = "./binaries/idchain-parachain-2"
#     ws_port = 9920
#     args = ["--log=xcm=trace,pallet-assets=trace"]